=== yaomeiguan/epiphany-sourceware/sid/component/component.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- this is the SID component documentation format.              -->
<!-- it's indended for translation to docbook, and also           -->
<!-- for interpretation by SID configuration systems.             -->


<!-- basic "human consumption" inline content                     -->
<!ENTITY % inline "name|title|em|tt|a|complib|component|pin|bus|attribute|accessor">

<!-- convenience hyperlink + formatting tags -->
<!ELEMENT bus (#PCDATA)>
<!ELEMENT pin (#PCDATA)>
<!ELEMENT attribute (#PCDATA)>
<!ELEMENT accessor (#PCDATA)>
<!ELEMENT component (#PCDATA)>
<!ELEMENT complib (#PCDATA)>

<!ELEMENT name (#PCDATA)>
<!ELEMENT title (%inline;)*>
<!ELEMENT em (%inline;)*>
<!ELEMENT tt (%inline;)*>
<!ELEMENT code (#PCDATA)*>

<!-- hyperlinking is very important for this stuff, so we extend  -->
<!-- the HTML linking model slightly with typed external links.   -->

<!ELEMENT a (%inline;)*>
<!ATTLIST a type (url|techdoc) "url">
<!ATTLIST a href CDATA #REQUIRED>



<!-- basic "human consumption" structural content                 -->
<!ENTITY % block "title?,(%inline;|p|ul|ol|table|code)*">
<!ELEMENT p (%block;)>
<!ELEMENT ul (title?,li*)>
<!ELEMENT ol (title?,li*)>
<!ELEMENT li (%block;)>
<!ELEMENT table (tr*)>
<!ELEMENT tr (th|td)*>
<!ELEMENT th (%inline;)*>
<!ELEMENT td (%inline;)*>


<!-- the main structure of the document is as such                -->
<!ELEMENT defcomplib (defcomponent,synop,func,env,refs?)>
<!ATTLIST defcomplib lib CDATA #REQUIRED>
<!ATTLIST defcomplib dlsym CDATA #REQUIRED>

<!ELEMENT synop (%block;)>
<!ELEMENT env (%block;)>
<!ELEMENT refs (%block;)>

<!-- the functionality section includes some machine-indexable    -->
<!-- material, such as names of behaviors and conventions        -->
<!-- but there's plenty of room for human annotation              -->

<!ELEMENT func (modelling,behavior*,convention*)>
<!ELEMENT modelling (%block;)>

<!-- conventions and behaviors must be named for purposes of     -->
<!-- indexing & xref, but may have comments (a block) inside      -->

<!ELEMENT behavior (%block;)>
<!ATTLIST behavior name CDATA #REQUIRED>

<!ELEMENT convention (%block;)>
<!ATTLIST convention name CDATA #REQUIRED>
<!ATTLIST convention supported (true|false) "true">



<!-- the parts of the document which may be interesting to a      -->
<!-- SID configuration processor                                  -->

<!ELEMENT defcomponent ((defpin|defbus|defattribute|defaccessor)*,variants?)>
<!ATTLIST defcomponent name CDATA #REQUIRED>
<!ATTLIST defcomponent type (abstract|concrete) "concrete">

<!ELEMENT variants (defcomponent+)>

<!ELEMENT defpin EMPTY>
<!ATTLIST defpin name CDATA #REQUIRED>
<!ATTLIST defpin direction (in|out|inout) #REQUIRED>
<!ATTLIST defpin legalvalues CDATA #IMPLIED>
<!ATTLIST defpin behaviors CDATA #REQUIRED>

<!ELEMENT defbus EMPTY>
<!ATTLIST defbus name CDATA #REQUIRED>
<!ATTLIST defbus addresses CDATA #IMPLIED>
<!ATTLIST defbus accesses CDATA #IMPLIED>
<!ATTLIST defbus behaviors CDATA #REQUIRED>

<!ELEMENT defattribute EMPTY>
<!ATTLIST defattribute name CDATA #REQUIRED>
<!ATTLIST defattribute category CDATA #IMPLIED>
<!ATTLIST defattribute legalvalues CDATA #REQUIRED>
<!ATTLIST defattribute defaultvalue CDATA #IMPLIED>
<!ATTLIST defattribute behaviors CDATA #REQUIRED>

<!ELEMENT defaccessor EMPTY>
<!ATTLIST defaccessor name CDATA #REQUIRED>
<!ATTLIST defaccessor accesses CDATA #IMPLIED>
<!ATTLIST defaccessor behaviors CDATA #REQUIRED>

=== yaomeiguan/epiphany-sourceware/sid/component/cfgroot/sid-control-dynamic-configurator.xml
<?xml version="1.0" ?>
<!DOCTYPE defcomplib SYSTEM "http://sources.redhat.com/sid/component.dtd">

<defcomplib lib="internal" dlsym="config_component_library">
  <defcomponent name="sid-control-dynamic-configurator" type="concrete">

    <!-- pins -->
    <defpin name="reset"		direction="in"  legalvalues="any"			behaviors="initialization" />
    <defpin name="step!"		direction="in"  legalvalues="any"			behaviors="running" />
    <defpin name="step-control"		direction="out" legalvalues="1"			behaviors="running" />
    <defpin name="configure!"		direction="in"  legalvalues="configuration handle"	behaviors="configuration" />
    <defpin name="config-result"	direction="out" legalvalues="configuration handle"	behaviors="configuration" />
    <defpin name="config-error"	        direction="out" legalvalues="error code"	behaviors="configuration" />
    <defpin name="function-caller!"	direction="in"  legalvalues="address"		behaviors="configuration" />
    <defpin name="function-callee!"	direction="in"  legalvalues="address"		behaviors="configuration" />
    <defpin name="function-jump!"	direction="in"  legalvalues="address"		behaviors="configuration" />
    <defpin name="function-return!"	direction="in"  legalvalues="address"		behaviors="configuration" />
    <defpin name="function-address"	direction="out" legalvalues="address"		behaviors="configuration" />

    
    <!-- attributes -->
    <defattribute name ="warmup-functions!"	default="function list" behaviors="configuration" />
    <defattribute name ="profile-functions!"	default="config spec"   behaviors="configuration" />
    <defattribute name ="configure!"		default="config name"   behaviors="configuration" />
    <defattribute name ="current-config"	default="config string" behaviors="configuration" />
    
    <!-- relationships -->
    <defrelationship name="client"	behaviors="configuration" />
    <defrelationship name="loader"	behaviors="configuration" />
    <defrelationship name="main"	behaviors="configuration" />
    
  </defcomponent>

  <synop>This component manages configuration profiles for a board.
  </synop>

  <func>
    <modelling>
      <p>
      This component manages dynamic configuration of a board based upon the setting of an
      attribute, the driving of an input pin and entry/exit to/from functions.  The selected
      configurations are made available to other components in the system which then reconfigure
      themselves accordingly.</p>

      <p>This component does not correspond to hardware.</p>
    </modelling>

    <behavior name="configuration">

      <p>
      When the <attribute>configure!</attribute> attribute is written to, the value is
      interpreted as the name of a configuration spec.  The corresponding configuration
      string is then obtained from the configuration root component by setting its
      <attribute>lookup-dynamic-config!</attribute> attribute and then, if successful,
      reading its <attribute>found-dynamic-config</attribute> attribute.  A numeric handle
      is assigned to this configuration. The handle of the previous configuration is driven
      on the <pin>config-result</pin> pin. If an error occurs, a non-zero
      value will be driven on the <pin>config-error</pin> pin.</p>

      <p>
      When the <pin>configure!</pin> pin is driven, the value is interpreted as
      the handle of a configuration which was previously driven on the <pin>config-result</pin>
      pin. This configuration is then selected and the handle of the previous configuration is
      driven on the <pin>config-result</pin>. If an error occurs, a non-zero
      value will be driven on the <pin>config-error</pin> pin.</p>

      <p>
      When the <attribute>profile-functions!</attribute> attribute is written to, the value is
      interpreted as a specification of the form FUNCTION_NAME[,FUNCTION_NAME]*:CONFIG_NAME,
      where FUNCTION_NAME is the name of a function in the target software and CONFIG_NAME is
      the name of a configuration specified to the configuration root component via its
      <attribute>dynamic-config</attribute> attribute. The listed functions are then associated
      with the named configuration.  The <pin>function-caller!</pin>, <pin>function-callee!</pin>,
      <pin>function-jump!</pin> and <pin>function-return!</pin> pins should be driven by the cpu
      component as the target software executes.  The values driven on these pins are interpreted as
      memory addresses containing executable code. The addresses are driven on the <pin>function-address</pin>,
      which should be connected to the <pin>function?</pin> pin of the board's loader component. The name
      of the corresponding function is then obtained from the loader's <attribute>current-function</attribute>
      attribute. If the named function is associated with a configuration, that configuration is then
      selected.</p>

      <p>
      When the <attribute>warmup-functions!</attribute> attribute is written to, the value is
      interpreted as a comma-separated list of function names in the target software.  The listed
      functions are then associated with the configuration named sid-internal-warmup.  When one of
      the listed functions is entered (see <attribute>profile-fuinctions!</attribute> above), this
      configuration is selected.  The special function _Sid_config should be specified as a
      warmup function and it does not restore the previous configuration when returning to the function
      which called it.</p>

    </behavior>

    <behavior name="initialization">

      <p>
      When the <pin>reset</pin> pin is driven, the configuration identified by the
      <attribute>start-config</attribute> attribute is selected.</p>

    </behavior>

    <behavior name="running">

      <p>
      When the <pin>step!</pin> is driven, and the currently selected configuration has changed since the previous
      time the <pin>step!</pin> was driven, the specifiction of the currently selected configuration is passed
      on the <pin>new-config</pin> and the string representing the current configuration is made available
      to each component related via the <relationship>client</relationship> by setting their
      <attribute>configure!</attribute> attributes. Each client is then responsible for interpreting the
      specification and configuring themselves accordingly.
      </p> 

      <p>
      When a new configuration is selected, using one of the methods above, the <pin>step-control</pin> is
      driven with the value 1.</p>

    </behavior>

    <convention name="supervisory" supported="true"/>
    <convention name="save/restore" supported="false">state is minimal.</convention>
    <convention name="triggerpoints" supported="false"/>
    <convention name="recursion-inhibit" supported="false"/>
    <convention name="categories" supported="false"/>

  </func>
  <env>
  </env>

  
</defcomplib>

=== yaomeiguan/epiphany-sourceware/sid/component/glue/hw-glue-pin-pacer.xml
<?xml version="1.0" ?>
<!DOCTYPE defcomplib SYSTEM "http://sources.redhat.com/sid/component.dtd">

<defcomplib lib="libglue.la" dlsym="glue_component_library">
  <defcomponent name="hw-glue-sequence" type="abstract">

    <!-- pins -->
    <defpin name="tick" direction="in" legalvalues="any" behaviors="data forwarding" />
    <defpin name="request_input" direction="out" legalvalues="any" behaviors="data forwarding" />
    <defpin name="input" direction="in" legalvalues="any" behaviors="data forwarding" />
    <defpin name="output" direction="out" legalvalues="any" behaviors="data forwarding" />

    <!-- attributes -->
    <defattribute name="state-snapshot" category="no category" legalvalues="opaque string" behaviors="state save/restore" />
    <defattribute name="signals-per-tick" category="setting, watchable" legalvalues="32 bit positive number" defaultvalue="1" behaviors="configuration" />
    <defattribute name="tick" category="pin, watchable" behaviors="data forwarding" />
    <defattribute name="request-input" category="pin, watchable" behaviors="data forwarding" />
    <defattribute name="input" category="pin, watchable" behaviors="data forwarding" />
    <defattribute name="output" category="pin, watchable" behaviors="data forwarding" />
  </defcomponent>
  <synop>
    <p>
      This component forwards signals received at its input to its output at a specified number of signals per tick.
      This is useful for simulating baud rates in serial devices.
    </p>
  </synop>
  <func>
    <modelling>
      <p>
	 This component is a fifo for pin signals.
      </p>
    </modelling>
    <behavior name="configuration">
      <p>
        <attribute>signals-per-tick</attribute> designates how many signal will be driven (if available) per incoming signal
	on the tick pin.
      </p>
    </behavior>
    <behavior name="data forwarding">
      <p>
	 This component is a fifo for pin signals. It will generate a duplicate pin signal on its output for every pin
	 signal on its input at the pace configured in the attribute <attribute>signals-per-tick</attribute>. These
	 signals will be generated whenever the tick input pin is driven. If the fifo contains less than signals-per-tick
	 signals when tick is driven, then request-input will be driven. If no further signals arrive when request-input
	 is driven, then output will be driven with whatever signals are available in the fifo. (If none are available,
	 then none will be driven.) The fifo size is limited only by memory on the simulating pc. Note that input rate is
	 not controlled. The device generating data (for example a stdio component or a socket component) can put data
	 into the fifo at whatver rate it desires, which will simply require more memory to store the data until it
	 can be driven out at the next tick. It is recommended that <pin>request-input</pin> be connected to the polling
	 pin on whatever device is connected to <pin>input</pin>. On the stdio component for example, this would replace
	 the input from a host scheduler.
      </p>
    </behavior>
    <convention name="functional" supported="true">
      <p>
	This is a functional component.</p>
    </convention>
    <convention name="state save/restore" supported="true">
      <p>
	This component supports state save/restore 
     </p>
    </convention>
    <convention name="triggerpoints" supported="true">
      <p>
	This component supports triggerpoints.
      </p>
    </convention>
    <convention name="Recursion Control" supported="true">
      <p>
	This component limits recursion on the <pin>input</pin> pin.</p>
    </convention>
    <convention name="presentation" supported="true">
      <p>
	This component presents attributes in the <name>pin</name>, <name>setting</name>, and <name>watchable</name> categories.</p>
    </convention>
  </func>
  <env>
      <p>
        This device is useful for modeling a baud rate on a serial device.
     </p>
  </env>
</defcomplib>

=== yaomeiguan/epiphany-sourceware/sid/component/rtc/hw-rtc-sid.xml
<?xml version="1.0" ?>
<!DOCTYPE defcomplib SYSTEM "http://sources.redhat.com/sid/component.dtd">

<defcomplib lib="librtc.la" dlsym="rtc_component_library">
  <defcomponent name="hw-rtc-sid" type="concrete">

    <defbus name="registers" addresses="0x0..0x7" accesses="read" behaviors="timing"/>

    <defattribute name="hour" category="register" legalvalues="0..23" behaviors="more timing"/>
    <defattribute name="minute" category="register" legalvalues="0..59" behaviors="more timing"/>
    <defattribute name="second" category="register" legalvalues="0..59" behaviors="more timing"/>
    <defattribute name="tk xclock clone" category="gui" legalvalues='"hw-visual-clock"' behaviors="component gui"/>

  </defcomponent>
  <synop>This component is a fictional simplified high-precision real time clock.
  </synop>
  <func>
    <modelling>This component is similar to high-precision dedicated counters
      present as performance tuning aids in some microprocessors.  It
      supplies snapshots of the host systems' time to a target application
    </modelling>

    <behavior name="timing">
      Whenever this component's bus is read with a valid address, it
      returns the addressed subset of two words of information.  The
      first word (address 0x0) contains the number of seconds since the
      host system's epoch.  The second word (address 0x4) contains the
      number of nanoseconds within that second.  Both words are supplied
      in big-endian order.
    </behavior>

    <behavior name="more timing">
    As a special bonus, the
      <attribute>hour</attribute>,
      <attribute>minute</attribute>, and
      <attribute>second</attribute>
    attributes contain the appropriate numbers for the current
    moment, in the GMT timezone.</behavior>
    
    
    <convention name="functional" supported="true"/>
    <convention name="triggerpoint" supported="false"/>
    <convention name="state save/restore" supported="false"/>
    <convention name="component gui" supported="true"/>

  </func>
  <env>
    
    <title>Related components</title>
    <ul>
      <li>
	<p>To use this component, map it into 8 bytes of address
	  space, as in the following sample configuration file fragment: </p>
	<code>
	  new hw-rtc-sid rtc
	  connect-bus mapper [0x1000,0x1007] rtc registers</code></li>
      
      <li>
	<p>
	  The "hw-visual-clock" component is a candidate gui for this
	  component.</p>
	
	<code>
	  new hw-rtc-sid rtc
	  new hw-visual-clock rtc-gui
	  relate rtc-gui "your rtc friend" rtc</code></li></ul>
    
    <title>Host system</title>
    <p>The component relies on the accuracy and precision of UTC time
      maintained by the host.</p>
  </env>
</defcomplib>

=== yaomeiguan/epiphany-sourceware/sid/component/profiling/sw-profile-gprof.xml
<?xml version="1.0" ?>
<!DOCTYPE defcomplib SYSTEM "http://sources.redhat.com/sid/component.dtd">

<defcomplib lib="libprof.la" dlsym="prof_component_library">
  <defcomponent name="sw-profile-gprof" type="concrete">

    <!-- pins -->
    <defpin name="sample" direction="in" legalvalues="any" behaviors="data gathering" />
    <defpin name="reset" direction="in" legalvalues="any" behaviors="data gathering" />
    <defpin name="store" direction="in" legalvalues="any" behaviors="profile generation" />


    <!-- attributes -->
    <defattribute name="value-count" category="register" legalvalues="decimal string" behaviors="data gathering" />
    <defattribute name="value-min" category="register" legalvalues="decimal string" behaviors="data gathering" />
    <defattribute name="value-max" category="register" legalvalues="decimal string" behaviors="data gathering" />
    <defattribute name="limit-min" category="setting" legalvalues="decimal string" defaultvalue="0" behaviors="data gathering" />
    <defattribute name="limit-max" category="setting" legalvalues="decimal string" defaultvalue="infinity" behaviors="data gathering" />
    <defattribute name="value-attribute" category="setting" legalvalues="name" defaultvalue="'pc'" behaviors="data gathering" />
    <defattribute name="output-file" category="setting" legalvalues="file name" defaultvalue="'gmon.out'" behaviors="configuration" />
    <defattribute name="output-file-endianness" category="setting" legalvalues="0/1/2/little/big/unknown" defaultvalue="unknown" behaviors="configuration" />
    <defattribute name="sample" category="pin" behaviors="data gathering" />
    <defattribute name="reset" category="pin" behaviors="data gathering" />
    <defattribute name="store" category="pin" behaviors="profile generation" />


    <!-- relationships -->
    <defrelationship name="target-component" behaviors="configuration" />
  </defcomponent>
  <synop>
    <p>
      This component accumulates profiling information from a target
      CPU and generates a gprof-compatible histogram file. 
    </p>
  </synop>
  <func>

    <modelling>
      <p>
	This component emulates profiling routines embedded in target
	programs, as if they were compiled with <tt>gcc -pg</tt>.
      </p>
    </modelling>

    <behavior name="configuration">
      <p>
      This component needs to be configured with the <relation>target-component</relation>
      relation.  The first element in the relation will be used as the
      target of profiling.  The <attribute>value-attribute</attribute> setting contains the
      name of the target component's attribute that will be collected.
      </p>
      <p>
      The <attribute>bucket-size</attribute> attribute configures the width of the
      histogram buckets.  It is invalid to change the bucket size if
      any samples have been accumulated (if <attribute>value-count</attribute> is nonzero).
      </p>
      <p>
      The <attribute>output-file</attribute> setting gives the name of the eventual profiling
      output file.  The <attribute>output-file-endianness</attribute> setting determines the
      endianness of the gprof formatted output.
      </p>
    </behavior>

    <behavior name="data gathering">
      <p>
      Whenever the <pin>sample</pin> pin is driven, this component takes a single
      sample of the configured target component's value attribute.  The
      attribute is interpreted as a numeric string, and the resulting
      number is accumulated in a big histogram, in the appropriate bucket.
      The bucket is chosen by masking the number into <attribute>bucket-size</attribute>-wide
      buckets.
      </p>
      <p>
      If the target component is unset, or its target attribute does not
      result in a valid numeric string, no sample is accumulated.  If a
      sample was collected, and falls between the <attribute>limit-min</attribute> and <attribute>limit-max</attribute>
      attributes' bounds, <attribute>value-count</attribute> is incremented, and <attribute>value-min</attribute>
      and <attribute>value-max</attribute> registers are updated.
      </p>
      <p>
      Whenever the <pin>reset</pin> pin is driven, the entire accumulated
      histogram and associated counters are discarded and a new count
      will be started.  It is not necessary to drive this pin at
      simulation startup.
      </p>
    </behavior>

    <behavior name="profile generation">
      Whenever the <pin>store</pin> pin is driven, this component dumps the entire
      accumulated histogram into a gprof (version 1) formatted file.  The
      file's endianness is chosen based on the <attribute>target-file-endianness</attribute>
      setting.  If it is unset, the target component's <attribute>endian</attribute> attribute
      will be queried and used if valid.

      The histogram is not automatically cleared after the store
      operation.  This makes it possible to save multiple generational
      profiling files to track history of a program cumulatively.  If
      the <pin>reset</pin> pin is triggered after every <pin>store</pin>, then separate
      intervals of the program's execution may be profiled.
    </behavior>


    <convention name="supervisory" supported="true" />
    <convention name="save/restore" supported="false" />
    <convention name="triggerpoints" supported="false" />
    <convention name="detect-reentrancy" supported="false" />
    <convention name="category" supported="true">
      It presents attributes in the <tt>pin</tt>, <tt>setting</tt> and categories.
    </convention>
  </func>
  <env>
    <title>
   Related components</title>
    <p>
     This component is typically connected to a CPU, and told to
      monitor the CPU's program counter (pc) register.  Sampling may
      be driven by any activity in SID, such as bus traffic (see
      <tt>hw-probe-bus</tt>), or host or target schedulers (see
      <tt>sid-sched-*</tt>).
      Perhaps the simplest way is to take a CPU PC sample every time
      the CPU has completed a batch of instructions.</p>

    <code>
	new sw-profile-gprof gprof
	new SOME_KIND_OF_CPU cpu
	relate gprof target-component cpu
	connect-pin shutdown-manager output-5 -&gt; gprof store
	connect-pin foo output -&gt; cpu step!
	connect-pin foo output -&gt; gprof sample
	# Set sampling interval by number of CPU instructions.
	set cpu step-insn-count 127
    </code>
    <title>
   Host system
    </title>
    <p>
    The amount of data tracked by this component may be very large,
      if <attribute>bucket-size</attribute> is small and the target value has a large number
      of distinct values.  Internally, a map or hash_map is used to
      track each bucket, so it does not matter how sparse the target
      value domain is.  However, at store time, each potential
      bucket in the histogram, from <attribute>value-min</attribute> to <attribute>value-max</attribute>, is
      recorded, so sparse values may generate large blocks of zeroes in
      the output.
    </p>
    <p>
     Since this component generates a histogram-type gprof file
      instead of the arc-type file that <tt>-pg</tt>-compiled target programs
      usually generate, gprof must be run with an option such as
      <tt>--flat-profile</tt>.  Call graph information is not collected.
    </p>
  </env>
</defcomplib>

=== yaomeiguan/epiphany-sourceware/sid/component/cgen-cpu/arm7t/hw-cpu-arm7t.xml
<?xml version="1.0" ?>
<!DOCTYPE defcomplib SYSTEM "http://sources.redhat.com/sid/component.dtd" [
<!ENTITY stdinterface SYSTEM "../common-xml/interface.xml">
<!ENTITY stdbehavior SYSTEM "../common-xml/behavior.xml">
<!ENTITY debugregisters SYSTEM "../common-xml/debugger-register-access.xml">
<!ENTITY stdconventions SYSTEM "../common-xml/conventions.xml">
<!ENTITY stdenvironment SYSTEM "../common-xml/environment.xml">
]>

<defcomplib lib="libcgencpu.la" dlsym="cgen_component_library">
  <defcomponent name="hw-cpu-arm7t" type="concrete">

    &stdinterface;

    <!-- pins -->
    <defpin name="nreset" direction="in" legalvalues="0 or 1" behaviors="execution" />
    <defpin name="nm" direction="out" legalvalues="0 or 1" behaviors="register access" />
    <defpin name="tbit" direction="out" legalvalues="0 or 1" behaviors="register access" />
    <defpin name="nfiq" direction="in" legalvalues="0 or 1" behaviors="hardware interrupts" />
    <defpin name="nirq" direction="in" legalvalues="0 or 1" behaviors="hardware interrupts" />

    <!-- attributes -->
    <defattribute name="cpsr" category="watchable register" legalvalues="number" behaviors="register access" />
    <defattribute name="cpsr-flags" category="register" legalvalues="string" behaviors="register access" />
    <defattribute name="nm" category="watchable pin" legalvalues="number" behaviors="register access" />
    <defattribute name="tbit" category="watchable pin" legalvalues="number" behaviors="register access" />
    <defattribute name="nfiq" category="watchable pin" legalvalues="number" behaviors="hardware interrupts" />
    <defattribute name="nirq" category="watchable pin" legalvalues="number" behaviors="hardware interrupts" />
    <defattribute name="rN_fiq" category="watchable register" legalvalues="number" behaviors="register access" />
    <defattribute name="rN_svc" category="watchable register" legalvalues="number" behaviors="register access" />
    <defattribute name="rN_abt" category="watchable register" legalvalues="number" behaviors="register access" />
    <defattribute name="rN_irq" category="watchable register" legalvalues="number" behaviors="register access" />
    <defattribute name="rN_und" category="watchable register" legalvalues="number" behaviors="register access" />
    <defattribute name="spsr_fiq" category="watchable register" legalvalues="number" behaviors="register access" />
    <defattribute name="spsr_svc" category="watchable register" legalvalues="number" behaviors="register access" />
    <defattribute name="spsr_abt" category="watchable register" legalvalues="number" behaviors="register access" />
    <defattribute name="spsr_irq" category="watchable register" legalvalues="number" behaviors="register access" />
    <defattribute name="spsr_und" category="watchable register" legalvalues="number" behaviors="register access" />
  </defcomponent>
  <synop>
    <p>This component models the ARM7 Thumb processor.</p>
  </synop>
  <func>
    <modelling>
	<p>This component models a simplified ARM7 Thumb processor.  </p>
	<p>It does not model floating point instructions.</p>
	<p>It models supervisory functions such as exceptions/traps in
	  order to be able to run an operating system.</p>
    </modelling>
    &stdbehavior;

    <behavior name="hardware interrupts">
      <p>Hardware interrupts are signalled by driving the pins
      <pin>nfiq</pin> or <pin>nirq</pin> with a zero value.  Incoming
      interrupts are queued and are processed when the
      <pin>step!</pin> pin is next invoked.  Note that this may not be
      the next instruction if the
      <attribute>step-insn-count</attribute> attribute is greater than
      one.</p>
    </behavior>


    <behavior name="register access">
      <p>All 16 general purpose registers are accessible as attribute
      <attribute>r0</attribute> through <attribute>r15</attribute>.
      <attribute>pc</attribute> is an alias of
      <attribute>r15</attribute>.  The CPSR register is accessible as
      <attribute>cpsr</attribute>, and also as
      <attribute>cpsr-flags</attribute> for a decoded textual form.
      The current endianness is available as attribute
      <attribute>endian</attribute>.  The current cpsr mode is
      available as attribute/pin <attribute>nm</attribute>.  The
      current thumb/arm bit is available as attribute/pin
      <attribute>tbit</attribute>.</p>

      <p>Banked registers (e.g. <attribute>r14_svc</attribute>,
      <attribute>spsr_und</attribute>) are also exposed as read/write
      attributes.</p>

    &debugregisters;
    </behavior>

  &stdconventions;
  </func>
  <env>
  &stdenvironment;
  </env>
  <refs>
  <p>ARM</p>
  <p>Arm Architecture Reference Manual, ARM DDI 0100B</p>
  </refs>

</defcomplib>
