=== yaomeiguan/epiphany-sourceware/sid/component/component.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- this is the SID component documentation format.              -->
<!-- it's indended for translation to docbook, and also           -->
<!-- for interpretation by SID configuration systems.             -->


<!-- basic "human consumption" inline content                     -->
<!ENTITY % inline "name|title|em|tt|a|complib|component|pin|bus|attribute|accessor">

<!-- convenience hyperlink + formatting tags -->
<!ELEMENT bus (#PCDATA)>
<!ELEMENT pin (#PCDATA)>
<!ELEMENT attribute (#PCDATA)>
<!ELEMENT accessor (#PCDATA)>
<!ELEMENT component (#PCDATA)>
<!ELEMENT complib (#PCDATA)>

<!ELEMENT name (#PCDATA)>
<!ELEMENT title (%inline;)*>
<!ELEMENT em (%inline;)*>
<!ELEMENT tt (%inline;)*>
<!ELEMENT code (#PCDATA)*>

<!-- hyperlinking is very important for this stuff, so we extend  -->
<!-- the HTML linking model slightly with typed external links.   -->

<!ELEMENT a (%inline;)*>
<!ATTLIST a type (url|techdoc) "url">
<!ATTLIST a href CDATA #REQUIRED>



<!-- basic "human consumption" structural content                 -->
<!ENTITY % block "title?,(%inline;|p|ul|ol|table|code)*">
<!ELEMENT p (%block;)>
<!ELEMENT ul (title?,li*)>
<!ELEMENT ol (title?,li*)>
<!ELEMENT li (%block;)>
<!ELEMENT table (tr*)>
<!ELEMENT tr (th|td)*>
<!ELEMENT th (%inline;)*>
<!ELEMENT td (%inline;)*>


<!-- the main structure of the document is as such                -->
<!ELEMENT defcomplib (defcomponent,synop,func,env,refs?)>
<!ATTLIST defcomplib lib CDATA #REQUIRED>
<!ATTLIST defcomplib dlsym CDATA #REQUIRED>

<!ELEMENT synop (%block;)>
<!ELEMENT env (%block;)>
<!ELEMENT refs (%block;)>

<!-- the functionality section includes some machine-indexable    -->
<!-- material, such as names of behaviors and conventions        -->
<!-- but there's plenty of room for human annotation              -->

<!ELEMENT func (modelling,behavior*,convention*)>
<!ELEMENT modelling (%block;)>

<!-- conventions and behaviors must be named for purposes of     -->
<!-- indexing & xref, but may have comments (a block) inside      -->

<!ELEMENT behavior (%block;)>
<!ATTLIST behavior name CDATA #REQUIRED>

<!ELEMENT convention (%block;)>
<!ATTLIST convention name CDATA #REQUIRED>
<!ATTLIST convention supported (true|false) "true">



<!-- the parts of the document which may be interesting to a      -->
<!-- SID configuration processor                                  -->

<!ELEMENT defcomponent ((defpin|defbus|defattribute|defaccessor)*,variants?)>
<!ATTLIST defcomponent name CDATA #REQUIRED>
<!ATTLIST defcomponent type (abstract|concrete) "concrete">

<!ELEMENT variants (defcomponent+)>

<!ELEMENT defpin EMPTY>
<!ATTLIST defpin name CDATA #REQUIRED>
<!ATTLIST defpin direction (in|out|inout) #REQUIRED>
<!ATTLIST defpin legalvalues CDATA #IMPLIED>
<!ATTLIST defpin behaviors CDATA #REQUIRED>

<!ELEMENT defbus EMPTY>
<!ATTLIST defbus name CDATA #REQUIRED>
<!ATTLIST defbus addresses CDATA #IMPLIED>
<!ATTLIST defbus accesses CDATA #IMPLIED>
<!ATTLIST defbus behaviors CDATA #REQUIRED>

<!ELEMENT defattribute EMPTY>
<!ATTLIST defattribute name CDATA #REQUIRED>
<!ATTLIST defattribute category CDATA #IMPLIED>
<!ATTLIST defattribute legalvalues CDATA #REQUIRED>
<!ATTLIST defattribute defaultvalue CDATA #IMPLIED>
<!ATTLIST defattribute behaviors CDATA #REQUIRED>

<!ELEMENT defaccessor EMPTY>
<!ATTLIST defaccessor name CDATA #REQUIRED>
<!ATTLIST defaccessor accesses CDATA #IMPLIED>
<!ATTLIST defaccessor behaviors CDATA #REQUIRED>

=== yaomeiguan/epiphany-sourceware/sid/component/families/mep/hw-interrupt-mep.xml
<?xml version="1.0" ?>
<!DOCTYPE defcomplib SYSTEM "http://sources.redhat.com/sid/component.dtd">

<defcomplib lib="libmepfamily.la" dlsym="mepfamily_component_library">
  <defcomponent name="hw-interrupt-mep" type="concrete">
    <variants>
      <defcomponent name="hw-interrupt-mep-1"  type="concrete"/>
      <defcomponent name="hw-interrupt-mep-2"  type="concrete"/>
      <defcomponent name="hw-interrupt-mep-3"  type="concrete"/>
      <defcomponent name="hw-interrupt-mep-4"  type="concrete"/>
      <defcomponent name="hw-interrupt-mep-5"  type="concrete"/>
      <defcomponent name="hw-interrupt-mep-6"  type="concrete"/>
      <defcomponent name="hw-interrupt-mep-7"  type="concrete"/>
      <defcomponent name="hw-interrupt-mep-8"  type="concrete"/>
      <defcomponent name="hw-interrupt-mep-9"  type="concrete"/>
      <defcomponent name="hw-interrupt-mep-10" type="concrete"/>
      <defcomponent name="hw-interrupt-mep-11" type="concrete"/>
      <defcomponent name="hw-interrupt-mep-12" type="concrete"/>
      <defcomponent name="hw-interrupt-mep-13" type="concrete"/>
      <defcomponent name="hw-interrupt-mep-14" type="concrete"/>
      <defcomponent name="hw-interrupt-mep-15" type="concrete"/>
      <defcomponent name="hw-interrupt-mep-16" type="concrete"/>
      <defcomponent name="hw-interrupt-mep-17" type="concrete"/>
      <defcomponent name="hw-interrupt-mep-18" type="concrete"/>
      <defcomponent name="hw-interrupt-mep-19" type="concrete"/>
      <defcomponent name="hw-interrupt-mep-20" type="concrete"/>
      <defcomponent name="hw-interrupt-mep-21" type="concrete"/>
      <defcomponent name="hw-interrupt-mep-22" type="concrete"/>
      <defcomponent name="hw-interrupt-mep-23" type="concrete"/>
      <defcomponent name="hw-interrupt-mep-24" type="concrete"/>
      <defcomponent name="hw-interrupt-mep-25" type="concrete"/>
      <defcomponent name="hw-interrupt-mep-26" type="concrete"/>
      <defcomponent name="hw-interrupt-mep-27" type="concrete"/>
      <defcomponent name="hw-interrupt-mep-28" type="concrete"/>
      <defcomponent name="hw-interrupt-mep-29" type="concrete"/>
      <defcomponent name="hw-interrupt-mep-30" type="concrete"/>
      <defcomponent name="hw-interrupt-mep-31" type="concrete"/>
      <defcomponent name="hw-interrupt-mep-32" type="concrete"/>
    </variants>

    <!-- pins -->
    <defpin name="reset" direction="in" legalvalues="any" behaviors="reset" />
    <defpin name="interrupt-source-[0,31]" direction="in" legalvalues="any" behaviors="interrupt processing" />
    <defpin name="interrupt" direction="out" legalvalues="-1 (inactive) or [0,31] (active)" behaviors="interrupt processing" />

    <!-- buses -->
    <defbus name="registers" addresses="0x0--0x1C" accesses="read/write" behaviors="register access" />

    <!-- attributes -->
    <defattribute name="reset" category="pin" legalvalues="any" behaviors="reset" />
    <defattribute name="interrupt" category="pin" legalvalues="-1, [0..31]" behaviors="interrupt processing" />
    <defattribute name="interrupt-level" category="read-only register" legalvalues="[1,3,7,15]" behaviors="interrupt processing" />
    <defattribute name="interrupt-mask-level" category="register" legalvalues="[1,3,7,15]" behaviors="interrupt processing" />
    <defattribute name="interrupt-channel-number" category="read-only register" legalvalues="[0..31]" behaviors="interrupt processing" />
    <defattribute name="interrupt-status-register" category="read-only register" legalvalues="any" behaviors="interrupt processing" />
    <defattribute name="interrupt-enable-register" category="read-only register" legalvalues="any" behaviors="interrupt processing" />
    <defattribute name="interrupt-edge-trigger-register" category="read-only register" legalvalues="any" behaviors="interrupt processing" />
    <defattribute name="interrupt-level-register-0" category="read-only register" legalvalues="any" behaviors="interrupt processing" />
    <defattribute name="interrupt-level-register-1" category="read-only register" legalvalues="any" behaviors="interrupt processing" />
    <defattribute name="interrupt-level-register-2" category="read-only register" legalvalues="any" behaviors="interrupt processing" />
    <defattribute name="interrupt-level-register-3" category="read-only register" legalvalues="any" behaviors="interrupt processing" />
    <defattribute name="interrupt-name-[0,31]" category="setting" legalvalues="any"/>

  </defcomponent>
  <synop>
    <p>
      This component simulates the Toshiba Media Engine (MeP) interrupt controller unit.</p>
  </synop>
  <func>
    <modelling>
      <p>
	<p>
	  The interrupt controller model features a configurable
	  number of (up to 32) general purpose interrupts.</p>
	<p>
	  The component models both edge and level triggered
	  interrupts.  When an interrupt source is configured as level
	  triggered, an interrupt source pin repeatedly driving the
	  same value will only constitute a single interrupt event.</p>
	</p>
    </modelling>

    <behavior name="reset">
      <p>
	When the <pin>reset</pin> input pin is driven, this component
	is reset to the hardware's normal power-up state.</p>
    </behavior>
    <behavior name="register access">
      <p>
	<p>
	  When the <bus>registers</bus> bus is accessed, the
	  appropriate 32-bit control register is read or written.

	  <table>
	    <tr>
	      <th>byte address</th>
	      <th>register</th>
	    </tr>
	    <tr>
	      <td>0x0</td>
	      <td>IVR</td>
	    </tr>
	    <tr>
	      <td>0x4</td>
	      <td>ISR</td>
	    </tr>
	    <tr>
	      <td>0x8</td>
	      <td>IER</td>
	    </tr>
	    <tr>
	      <td>0xC</td>
	      <td>IET</td>
	    </tr>
	    <tr>
	      <td>0x10</td>
	      <td>ILR0</td>
	    </tr>
	    <tr>
	      <td>0x14</td>
	      <td>ILR1</td>
	    </tr>
	    <tr>
	      <td>0x18</td>
	      <td>ILR2</td>
	    </tr>
	    <tr>
	      <td>0x1C</td>
	      <td>ILR3</td>
	    </tr>
	  </table>
	</p>
      </p>
    </behavior>
    <behavior name="interrupt processing">
      <p>
	When any interrupt source is signalled, or interrupt-enabled
	masks are modified, pending interrupts are processed.  Subject
	to the then-current interrupt-enabling registers, the
	<pin>interrupt</pin> output pin may be driven with a value
	representing the interrupt channel that was chosen.</p>
      
      <p>
	The polarity for the input source pins are positive, meaning
	that non-zero values are interpreted as <em>asserted</em>.</p>

      <p>
	Similarly named attributes may be used to generate/monitor pin
	traffic.</p>
    </behavior>
    <convention name="functional" supported="true">
      <p>
	This is a functional component.</p>
    </convention>
  </func>
  <env>
    <title>
      Related components</title>
    <p>
      The interrupt controller typically sits between a CPU component,
      which usually has only one interrupt pin, and an array of other
      peripheral components.  Each of the peripheral components is
      capable of generating its own interrupt.  The following
      configuration file fragment demonstrates how to connect two
      simple timers into the interrupt subsystem of a more complete
      simulation:
      
      <code>
	new hw-cpu-mep cpu
	new hw-timer-arm/ref-nosched timer1
	new hw-timer-arm/ref-nosched timer2
	new hw-interrupt-mep intc
        connect-pin timer1 interrupt -&gt; intc interrupt-source-0
	connect-pin timer2 interrupt -&gt; intc interrupt-source-1
	connect-pin intc interrupt -&gt; cpu irq</code></p>
  </env>
</defcomplib>

=== yaomeiguan/epiphany-sourceware/sid/component/consoles/sid-io-stdio.xml
<?xml version="1.0" ?>
<!DOCTYPE defcomplib SYSTEM "http://sources.redhat.com/sid/component.dtd">

<defcomplib lib="libconsoles.la" dlsym="console_component_library">
  <defcomponent name="sid-io-stdio" type="concrete">


    <!-- pins -->
    <defpin name="poll" direction="in" legalvalues="N/A" behaviors="input" />
    <defpin name="stdin" direction="out" legalvalues="any character code" behaviors="input" />
    <defpin name="eof" direction="out" legalvalues="boolean" behaviors="input" />
    <defpin name="stdout" direction="in" legalvalues="any character code" behaviors="output" />


    <!-- attributes -->
    <defattribute name="state-snapshot" legalvalues="opaque string" behaviors="state save/restore" />
  </defcomponent>
  <synop>
  This component performs input/output on the standard input/output. 
  </synop>
  <func>
    <modelling>

<p>
    This component acts as an interface between the host system's
    stdio streams and pins in the simulated system.
</p>

<p>
    This component uses non-blocking I/O on the host. It cannot use
    blocking I/O because the entire simulation would block. As a
    result, this component requires time slices from the simulator to
    check for pending data that must be read from <tt>stdin</tt>.  To do this,
    you can use a common scheduler component (<complib>sid-sched-*</complib>) to
    efficiently yield time to the <component>sid-io-stdio</component>
    component.  However, you should carefully consider the choice of
    the time interval to be used by the scheduler.  We recommend
    approximately 10 times per second.
</p>
    </modelling>

    <behavior name="output">
    When the <pin>stdout</pin> input pin is driven with a value between 0 and
    255, the value is immediately written to stdout.
    </behavior>

    <behavior name="input">
    When the <pin>poll</pin> pin is driven, the <tt>stdin</tt> stream is checked for
    unread input, without blocking.  If end of file has not been detected, the <pin>eof</pin>
    pin is driven with the value 0. All available input is consumed,
    and transmitted individually by driving the <pin>stdin</pin> pin with each
    byte, in sequence. When end of file is detected, the <pin>eof</pin> is driven with
    a value of 1 and no data is transmitted via the <pin>stdin</pin> pin.

    </behavior>

    <convention name="functional" supported="true"/>
    <convention name="save/restore" supported="true">
      <p>null state save/restore.</p>
    </convention>
  </func>
  
  

  <env>
    <title>Related components</title>

<p>
    See sid-io-fileio for writing to a stream.
</p>
<p>
    You can connect a stdio console to a serial data transmission
    component, such as a UART. You can also connect it to a 
    ROM monitor/system call emulator, such as the <complib>sw-gloss-arm/angel</complib> 
    which performs I/O across some sort of debug channel.
    In order for a stdio console component to collect data from
    standard input without blocking the entire simulation,
    non-blocking I/O is used. It is necessary to give simulation time
    to the component to collect any data from stdin and to buffer the data.
    To do this, you can use the common scheduler component (see
    Functionality, Modelling).
</p>    

<p>
    The following is an example of how a stdio console might be 
    configured to connect into a system:
</p>

<code>	new sid-sched-host sched
	new sw-gloss-arm/angel angel
	new sid-io-stdio stdio
	set sched enabled? 1
	set sched num-clients 1
	set sched 0-regular? 1
	set sched 0-time 50
	connect-pin sched 0-event -&gt; stdio poll
	connect-pin angel debug-tx -&gt; stdio stdout
	connect-pin angel debug-rx &lt;- stdio stdin

</code>
  </env>
</defcomplib>

=== yaomeiguan/epiphany-sourceware/sid/component/mmu/hw-remap_pause-arm_ref.xml
<?xml version="1.0" ?>
<!DOCTYPE defcomplib SYSTEM "http://sources.redhat.com/sid/component.dtd">

<defcomplib lib="libmmu.la" dlsym="mmu_component_library">
  <defcomponent name="hw-remap/pause-arm/ref" type="concrete">


    <!-- pins -->
    <defpin name="reset" direction="in" legalvalues="0 or non-zero" behaviors="resetting" />
    <defpin name="halt!" direction="out" legalvalues="0 or non-zero" behaviors="halting" />


    <!-- buses -->
    <defbus name="access-port" addresses="all addresses" accesses="any" behaviors="remapping" />
    <defbus name="registers" addresses="0x0 to 0x37" accesses="read/write words" behaviors="register access" />


    <!-- accessors -->
    <defaccessor name="all" accesses="any bus operation" behaviors="remapping" />


    <!-- attributes -->
    <defattribute name="remapping?" category="setting" legalvalues="boolean string" defaultvalue="true" behaviors="remapping, remapping setup" />
    <defattribute name="num-relocations" legalvalues="numeric string" defaultvalue="0" behaviors="remapping setup" />
    <defattribute name="N-start" category="setting" legalvalues="numeric string" behaviors="remapping setup" />
    <defattribute name="N-end" category="setting" legalvalues="numeric string" behaviors="remapping setup" />
    <defattribute name="N-reloc-to" category="setting" legalvalues="numeric string" behaviors="remapping setup" />
  </defcomponent>

  <synop>
    <p> The remap and pause controller, present on the ARM PID7T
    board, handles four rather independent functions:
    </p>
    <ul>
      <li>Identification</li>
      <li>Remapping of memory (such that, for instance, a power-on
	reset of the board will cause a ROM to be mapped to address 0)</li>
      <li>Pausing the CPU until an interrupt occurs.</li>
      <li>Checking for reset status ("was the board just reset?")</li>
    </ul>
  </synop>
  <func>
    <modelling>
      <p>The controller has a variety of functions, most of which are
      trivial to simulate.  A minimal implementation is provided for
      controller identification.  The most complex aspect of this
      component is how remapping is handled.  During boot-up, the
      controller uses a "reset map" that maps a range of addresses to
      some other location (typically address 0).  At some point, the
      target program will write to one of the controller's registers,
      causing it to switch to a "normal map", in which case no address
      translation occurs. </p>

      <p>In order for the mapping to occur, this controller must be
      placed between the CPU and other components, such as peripherals
      and the main memory.  This additional level of indirection for
      bus traffic (particularly between a CPU and memory) may
      introduce performance penalties.  This controller should be used
      only when necessary.  Even then, it is possible to route bus
      traffic around this component if the remapping facility is not
      required.</p>

    </modelling>


    <behavior name="register access">
      <p> The <bus>registers</bus> bus provides read/write access to
      the internal registers of the remap/pause controller.  The
      memory map of the register set is shown below.  More detail
      about each of these registers can be found in the ARM
      documentation (see ``References'').</p>
	<table>	  
	  <tr>                <th>address</th>         <th>read</th>            <th>write</th></tr>
	  <tr>               <td>0</td>               <td>(reserved)</td>     <td> pause</td></tr>
	  <tr>               <td>+ 0x10</td>          <td>identification</td>  <td>(reserved)</td></tr>
	  <tr>                <td>+ 0x20</td>          <td>(reserved)</td>      <td>clear reset map</td></tr>
	  <tr>                <td>+ 0x30</td>          <td>reset status</td>    <td>reset status set</td></tr>
	  <tr>                <td>+ 0x34</td>          <td>(reserved)</td>      <td>reset status clear</td></tr>
	</table>
    </behavior>

    <behavior name="resetting">
      <p>
        If the <pin>reset</pin> pin is driven with a non-zero value,
        the reset status is updated within the component such that
        interrogating the controller's reset status will indicate that
        a power on reset has occurred.
      </p>
    </behavior>

    <behavior name="halting">
      <p>
        The <pin>halt!</pin> pin may be connected to a component such
        as an ARM CPU which knows to halt instruction processing when
        the pin is driven with a non-zero value.  This pin will be
        driven when the pause register is written to.
      </p>
    </behavior>

    <behavior name="remapping">
      <p>
        This <bus>access-port</bus> bus provides upstream access the
        remapper function in this component.  Reads/writes to this bus
        are translated (if appropriate) and passed onto the second
        bus, as set by the <accessor>all</accessor> accessor.
      </p>
    </behavior>

    <behavior name="remapping setup">
      <p>
        The <attribute>remapping?</attribute> attribute specifies
        which memory map will be used.  It is anticipated that this
        attribute will be used at the start of a simulation session to
        provide the equivalent of a jumper for enabling the reset or
        the normal memory map at power-up.  If the attribute is set to
        `yes', then any relocations that have been defined will
        apply. As usual, writing to the `clear reset map' register
        will cause the normal map to be used.
      </p>
      <p>
        Please note that the polarity of the
        <attribute>remapping?</attribute> flag is opposite to some ARM
        documentation.  ARM refers to a "Normal (Remapped)" condition
        on the PID7T board when the customary sid mapping is disabled,
        and "Reset" mapping condition when the customary sid mapping
        is enabled.  This is just a terminology and sid configuration
        policy issue.
      </p>
      <p>
        The <attribute>num-relocations</attribute> attribute specifies
        how many relocations are to be defined via the numeric N-
        attributes (see below).  This serves little purpose other than
        to dynamically generate the N- attributes necessary for
        defining the relocations.  Note: this attribute may only be
        set once.
      </p>
      <p>
        The <attribute>N-start</attribute> family of attributes
        specify the starting addresses of a memory regions that are to
        be relocated to a different location.  If there are three
        available relocations (due to setting
        <attribute>num-relocations</attribute> to 3), then there will
        be three sets of attributes, prefixed by 0-, 1-, and 2-.  The
        first starting address attribute is 0-start.
      </p>
      <p>
        The <attribute>N-end</attribute> family of attributes specify
        the end of the memory regions that are to be relocated to a
        different location.  Usually, this is: <tt>(base + limit) -
        1</tt> That is, the address given to the N-start and N-end
        attributes are all inclusive.
      </p>
      <p>
        The <attribute>N-reloc-to</attribute> family of attributes
        specify the addresses to which region N will be relocated.
      </p>
    </behavior>

    <convention name="functional" supported="true" />
    <convention name="save/restore" supported="true" />
    <convention name="triggerpoints" supported="true">
      <p>It provides a single attribute-based triggerpoint,
      <attribute>remapping?</attribute>.</p>
    </convention>
  </func>
  <env>
    <title>Related components</title>
    <ul>
      <li>
	<p>This component usually sits between a CPU and the remaining
	components of a complete system (in order to handle the
	remapping discussed above).  Thus, the CPU's data and
	instruction memory accesses are routed through this component.
	This component would then be connected to the traditional
	mapper component which will redirect bus traffic based on the
	target address.</p></li>
      
      <li><p>A configuration file fragment illustrating this idea appears
	  below:</p>
	<code>
        new hw-remap/pause-arm/ref remapper
        new hw-mapper-basic bus
        new hw-cpu-arm7t cpu
        connect-bus cpu insn-memory remapper access-port
        connect-bus cpu data-memory remapper access-port
        connect-bus remapper all bus access-port
	</code></li>
      </ul>    
  </env>

  <refs>
  More details about this controller can be found <a type="url"
  href="http://www.arm.com/Documentation/UserMans/rps/#rp">on the
  web</a>.
  </refs>

</defcomplib>
