=== yaomeiguan/epiphany-sourceware/sid/component/component.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- this is the SID component documentation format.              -->
<!-- it's indended for translation to docbook, and also           -->
<!-- for interpretation by SID configuration systems.             -->


<!-- basic "human consumption" inline content                     -->
<!ENTITY % inline "name|title|em|tt|a|complib|component|pin|bus|attribute|accessor">

<!-- convenience hyperlink + formatting tags -->
<!ELEMENT bus (#PCDATA)>
<!ELEMENT pin (#PCDATA)>
<!ELEMENT attribute (#PCDATA)>
<!ELEMENT accessor (#PCDATA)>
<!ELEMENT component (#PCDATA)>
<!ELEMENT complib (#PCDATA)>

<!ELEMENT name (#PCDATA)>
<!ELEMENT title (%inline;)*>
<!ELEMENT em (%inline;)*>
<!ELEMENT tt (%inline;)*>
<!ELEMENT code (#PCDATA)*>

<!-- hyperlinking is very important for this stuff, so we extend  -->
<!-- the HTML linking model slightly with typed external links.   -->

<!ELEMENT a (%inline;)*>
<!ATTLIST a type (url|techdoc) "url">
<!ATTLIST a href CDATA #REQUIRED>



<!-- basic "human consumption" structural content                 -->
<!ENTITY % block "title?,(%inline;|p|ul|ol|table|code)*">
<!ELEMENT p (%block;)>
<!ELEMENT ul (title?,li*)>
<!ELEMENT ol (title?,li*)>
<!ELEMENT li (%block;)>
<!ELEMENT table (tr*)>
<!ELEMENT tr (th|td)*>
<!ELEMENT th (%inline;)*>
<!ELEMENT td (%inline;)*>


<!-- the main structure of the document is as such                -->
<!ELEMENT defcomplib (defcomponent,synop,func,env,refs?)>
<!ATTLIST defcomplib lib CDATA #REQUIRED>
<!ATTLIST defcomplib dlsym CDATA #REQUIRED>

<!ELEMENT synop (%block;)>
<!ELEMENT env (%block;)>
<!ELEMENT refs (%block;)>

<!-- the functionality section includes some machine-indexable    -->
<!-- material, such as names of behaviors and conventions        -->
<!-- but there's plenty of room for human annotation              -->

<!ELEMENT func (modelling,behavior*,convention*)>
<!ELEMENT modelling (%block;)>

<!-- conventions and behaviors must be named for purposes of     -->
<!-- indexing & xref, but may have comments (a block) inside      -->

<!ELEMENT behavior (%block;)>
<!ATTLIST behavior name CDATA #REQUIRED>

<!ELEMENT convention (%block;)>
<!ATTLIST convention name CDATA #REQUIRED>
<!ATTLIST convention supported (true|false) "true">



<!-- the parts of the document which may be interesting to a      -->
<!-- SID configuration processor                                  -->

<!ELEMENT defcomponent ((defpin|defbus|defattribute|defaccessor)*,variants?)>
<!ATTLIST defcomponent name CDATA #REQUIRED>
<!ATTLIST defcomponent type (abstract|concrete) "concrete">

<!ELEMENT variants (defcomponent+)>

<!ELEMENT defpin EMPTY>
<!ATTLIST defpin name CDATA #REQUIRED>
<!ATTLIST defpin direction (in|out|inout) #REQUIRED>
<!ATTLIST defpin legalvalues CDATA #IMPLIED>
<!ATTLIST defpin behaviors CDATA #REQUIRED>

<!ELEMENT defbus EMPTY>
<!ATTLIST defbus name CDATA #REQUIRED>
<!ATTLIST defbus addresses CDATA #IMPLIED>
<!ATTLIST defbus accesses CDATA #IMPLIED>
<!ATTLIST defbus behaviors CDATA #REQUIRED>

<!ELEMENT defattribute EMPTY>
<!ATTLIST defattribute name CDATA #REQUIRED>
<!ATTLIST defattribute category CDATA #IMPLIED>
<!ATTLIST defattribute legalvalues CDATA #REQUIRED>
<!ATTLIST defattribute defaultvalue CDATA #IMPLIED>
<!ATTLIST defattribute behaviors CDATA #REQUIRED>

<!ELEMENT defaccessor EMPTY>
<!ATTLIST defaccessor name CDATA #REQUIRED>
<!ATTLIST defaccessor accesses CDATA #IMPLIED>
<!ATTLIST defaccessor behaviors CDATA #REQUIRED>

=== yaomeiguan/epiphany-sourceware/sid/component/mapper/hw-mapper-basic.xml
<?xml version="1.0" ?>
<!DOCTYPE defcomplib SYSTEM "http://sources.redhat.com/sid/component.dtd">

<defcomplib lib="libmapper.la" dlsym="mapper_component_library">
  <defcomponent name="hw-mapper-basic" type="concrete">


    <!-- buses -->
    <defbus name="access-port" addresses="any address" accesses="any access" behaviors="mapping" />


    <!-- accessors -->
    <defaccessor name="ACCESSOR, any of the specified forms" accesses="any access" behaviors="configuration, mapping" />


    <!-- attributes -->
    <defattribute name="access-count" category="register" legalvalues="number" defaultvalue="0" behaviors="mapping" />
    <defattribute name="cache-hit-count" category="register" legalvalues="number" defaultvalue="0" behaviors="mapping" />
    <defattribute name="ACCESSOR-count" category="register" legalvalues="number" defaultvalue="0" behaviors="mapping" />
    <defattribute name="latency" category="setting" legalvalues="number" defaultvalue="0" behaviors="memory latency" />
    <defattribute name="state-snapshot" legalvalues="opaque string" behaviors="state save/restore" />
  </defcomponent>
  <synop>
    <p>
      This component is a generalized model of the distributed computer
      circuitry that decodes bus addresses.</p>
  </synop>
  <func>
    <modelling>
      <p>
	<p>
	  This component distributes bus accesses to one of a number of
	  configured bus accessors, depending on the address of the
	  incoming memory access.</p>  
	<p>
	  A mapper defines an address space.  The address space is
	  decomposed into non-overlapping regions by configuring a dynamic
	  collection of accessors.  Each accessor is connected to a single
	  slave bus.  To configure the address mapping, you must name each 
	  accessor according to one of these forms:
	  
	  <ul>
	    <li><tt>[&lt;low&gt;-&lt;high&gt;]</tt></li>
	    <li><tt>[&lt;low&gt;-&lt;high&gt;,&lt;wordsize&gt;]</tt></li>
	    <li><tt>[&lt;low&gt;-&lt;high&gt;,&lt;stride&gt;,&lt;width&gt;]</tt></li>
	    <li><tt>[&lt;low&gt;-&lt;high&gt;,&lt;stride&gt;,&lt;width&gt;,&lt;wordsize&gt;]</tt></li>
	  </ul>

	  where:
	  <ul>
	  <li><tt>
	    &lt;low&gt;</tt> is the starting address for the mapped region. </li>
	  <li><tt>
	    &lt;high&gt;</tt> is the ending address for the mapped region. </li>
	  <li><tt>
	    &lt;stride&gt;</tt> is the step size between addressable units. </li>
	  <li><tt>
	    &lt;width&gt;</tt> is the width of addressable units. </li> 
	  <li><tt>
	    &lt;wordsize&gt;</tt> is the number of bytes in an address unit:
	  a constant multiplier you can use to permit specifying &lt;low&gt;, &lt;high&gt;,
	  &lt;stride&gt; and &lt;width&gt; in terms of multi-byte words.</li>
	  </ul>
	</p>
	
	<p>
	  In addition, any text may appear outside the "[" and "]" brackets,
	  as long as that text does not include any of the separator
	  characters "[" "]" "-" ",".</p>
	
	<p>
	  Each number may be specified in decimal, hexadecimal, octal, and
	  binary forms, with the appropriate prefix (none, "0x", "0",
	  "0b", respectively).</p>
	
	<p>
	  The first form is appropriate if the slave device is willing to
	  accept all possible sid::bus accesses (subject to the address
	  range limits).  The second form is appropriate if the slave
	  device is willing to accept only accesses to addressable units
	  of fixed width at a fixed stride from one another.</p>
	
	<p>
	  See the "mapping" behavior below for more details.</p></p>
    </modelling>
    <behavior name="configuration">
      <p>
	<p>
	  When an accessor of the prescribed format is set, and the
	  address range is valid, the supplied bus is registered in the
	  decoding table.  Future accesses on the <bus>access-port</bus> bus will
	  consider that address range as a candidate.</p>
	<p>
	  Reasons for rejecting an address range include overlapping with
	  an existing entry, or inconsistent ranges or stride/width
	  values.</p></p>
    </behavior>
    <behavior name="mapping">
      <p>
	<p>
	  When an incoming access on the <bus>access-port</bus> bus is
	  received, its base address is compared to all the registered
	  outgoing accessors.  If one is found that contains the
	  address, the current address is transformed according to the
	  following rules:

	  <ul>
	    <li>
	      The accessor's &lt;low&gt; address is subtracted from the incoming
	      address, so outgoing addresses will be relative and zero-based.</li>
	    <li>
	      If the accessor has stride/width values, divide the relative
	      address by the quotient (&lt;stride&gt;/&lt;width&gt;).  As a result,
	      outgoing addresses will refer to consecutive addressable units, 
	      and an outgoing access of the desired width will be made.</li>
	    <li>
	      If the accessor has no stride/width values, the relative
	      address and the incoming access width will be used to make
	      an outgoing access.</li></ul></p>
	
	<p>
	  This component will return an incoming access prematurely with
	  <tt>sid::bus::unmapped</tt> if no accessor covers the incoming address.
	  Similarly, it will signal a <tt>sid::bus::misaligned</tt> condition if
	  an incoming access could be handled by a stride/width accessor,
	  but the addressed bytes don't cover exactly one addressable
	  unit.</p>
	
	<p>
	  Whenever an incoming access is attempted, the component
	  increments its <attribute>access-count</attribute> attribute.  When a repeated access
	  hits an internal mapping cache, the <attribute>cache-hit-count</attribute> is
	  incremented.  Whenever an incoming address is contained in a
	  specific accessor's address interval, the <attribute>ACCESSOR-count</attribute>
	  attribute is incremented.  (The ACCESSOR string is the name of
	  the accessor.)</p></p>
    </behavior>
    <behavior name="memory latency">
      <p>
        <p>
          This component models constant latency for accesses which
          pass through the mapper.  The value of the
          <attribute>latency</attribute> is added to the total latency
          of every bus transaction.  The units of latency are nominal,
          but typically represent a number of system clock
          cycles.</p></p>
    </behavior>
    <convention name="functional" supported="true">
      <p>
	This is a functional component.</p>
    </convention>
    <convention name="latency" support="true">
      <p>
        This component models memory latency.</p>
    </convention>
    <convention name="triggerpoints" supported="false">
      <p>
	This component does not support triggerpoints.</p>
    </convention>
    <convention name="state save/restore" supported="false">
      <p>
	This component does not support state save/restore.</p>
    </convention>
  </func>
  <env>
    <p>
    <title>
	Related components</title>
      <p>
	Commonly, this component will be placed between a CPU and an
	array of bus peripherals.  The hw-glue-probe-bus component may
	be used in conjunction with this component to analyze and
	troubleshoot bus configuration problems, being chained to either
	the CPU side of the mapper or the peripherals side.
      </p>
      <p>
	An illustration of a simple configuration for an ARM7T system
	with a main memory and a memory mapped UART follows:
	
	<code>	new hw-cpu-arm7t cpu
	new hw-mapper-basic bus
	new hw-uart-ns16550
	new hw-memory-ram/rom-basic mem
	set mem size 4194304
	connect-bus cpu insn-memory bus access-port
	connect-bus cpu data-memory bus access-port
	connect-bus bus [0xD800000,0xD80001F,4,1] uart Bus
	connect-bus bus [0x0,0x400000] mem read-write-port</code>
	
	Here, the CPU's accessors are connected directly to the mapper.
	All peripherals are connected downstream from the mapper.  They
	will have their bus transactions routed to them by the mapper,
	by virtue of configuration.</p></p>
  </env>
</defcomplib>

=== yaomeiguan/epiphany-sourceware/sid/component/parport/hw-parport-ps_2.xml
<?xml version="1.0" ?>
<!DOCTYPE defcomplib SYSTEM "http://sources.redhat.com/sid/component.dtd">

<defcomplib lib="libparport.la" dlsym="parport_component_library">
  <defcomponent name="hw-parport-ps/2" type="concrete">
    <!-- pins -->
    <defpin name="STROBE" direction="out" legalvalues="0, 1" behaviors="parallel i/o" />
    <defpin name="AUTOFDXT" direction="out" legalvalues="0, 1" behaviors="parallel i/o" />
    <defpin name="SLCTIN" direction="out" legalvalues="0, 1" behaviors="parallel i/o" />
    <defpin name="INIT" direction="out" legalvalues="0, 1" behaviors="parallel i/o" />
    <defpin name="INTP" direction="out" legalvalues="0, 1" behaviors="parallel i/o" />
    <defpin name="ERROR" direction="in" legalvalues="0, 1" behaviors="parallel i/o" />
    <defpin name="SLCT" direction="in" legalvalues="0, 1" behaviors="parallel i/o" />
    <defpin name="PE" direction="in" legalvalues="0, 1" behaviors="parallel i/o" />
    <defpin name="ACK" direction="in" legalvalues="0, 1" behaviors="parallel i/o" />
    <defpin name="BUSY" direction="in" legalvalues="0, 1" behaviors="parallel i/o" />
    <defpin name="INTSEL" direction="in" legalvalues="0, 1" behaviors="parallel i/o" />
    <defpin name="BIDEN" direction="in" legalvalues="0, 1" behaviors="parallel i/o" />
    <defpin name="RESET" direction="in" legalvalues="any" behaviors="reset" />
    <defpin name="PD0..PD7" direction="inout" legalvalues="0, 1" behaviors="parallel i/o" />


    <!-- buses -->
    <defbus name="Bus" addresses="0x00 - 0x02" accesses="byte-wide-access only" behaviors="register access" />


    <!-- attributes -->
    <defattribute name="STROBE" category="pin" legalvalues="0, 1" behaviors="parallel i/o" />
    <defattribute name="AUTOFDXT" category="pin" legalvalues="0, 1" behaviors="parallel i/o" />
    <defattribute name="SLCTIN" category="pin" legalvalues="0, 1" behaviors="parallel i/o" />
    <defattribute name="INIT" category="pin" legalvalues="0, 1" behaviors="parallel i/o" />
    <defattribute name="INTP" category="pin" legalvalues="0, 1" behaviors="parallel i/o" />
    <defattribute name="ERROR" category="pin" legalvalues="0, 1" behaviors="parallel i/o" />
    <defattribute name="SLCT" category="pin" legalvalues="0, 1" behaviors="parallel i/o" />
    <defattribute name="PE" category="pin" legalvalues="0, 1" behaviors="parallel i/o" />
    <defattribute name="ACK" category="pin" legalvalues="0, 1" behaviors="parallel i/o" />
    <defattribute name="BUSY" category="pin" legalvalues="0, 1" behaviors="parallel i/o" />
    <defattribute name="INTSEL" category="pin" legalvalues="0, 1" behaviors="parallel i/o" />
    <defattribute name="BIDEN" category="pin" legalvalues="0, 1" behaviors="parallel i/o" />
    <defattribute name="RESET" category="pin" legalvalues="any" behaviors="reset" />
    <defattribute name="PD0..PD7" category="pin" legalvalues="0, 1" behaviors="parallel i/o" />
    <defattribute name="PR" category="register" legalvalues="numeric string" behaviors="register access" />
    <defattribute name="SR" category="register" legalvalues="numeric string" behaviors="register access" />
    <defattribute name="COM" category="register" legalvalues="numeric string" behaviors="register access" />
    <defattribute name="CON" category="register" legalvalues="numeric string" behaviors="register access" />
    <defattribute name="IOSEL" category="register" legalvalues="numeric string" behaviors="register access" />
    <defattribute name="state-snapshot" legalvalues="opaque string" behaviors="state save/restore" />

  </defcomponent>
  <synop>
  <p>This component models a PS/2-style parallel port controller.</p>
  </synop>
  <func>
    <modelling>
    <p>The PS/2 parallel port controller is a simple 8-bit I/O
      interface to a printer.  From its origins, the parallel port
      system has evolved into higher functionality IEEE-1284
      controllers, but this sid component implements a version of the
      simple original standard.</p>

    <p>The specific hardware being modelled is the parallel port part
      of the Exar 16C552 device.</p>
    </modelling>

    <behavior name="register access">

      <p>Byte-wide operations on the <bus>registers</bus> bus access control
      registers of the model.  The control registers are also exported
      as attributes.</p>
      <table>
	<tr>	  <td>name</td>            <td>address</td>       <td>values</td>        <td>permitted accesses</td></tr>
	<tr>      <td>Port</td>		 <td>0x00</td>	       <td>0x00 - 0xFF</td>  <td>read/write</td></tr>
	<tr>	  <td>IO Select</td>	 <td>0x01</td>	       <td>0x00 - 0xFF</td>  <td>write</td></tr>
	<tr>	  <td>Control</td>        <td>0x02</td>	       <td>0xC0 - 0xFF</td>  <td>write</td></tr>
	<tr>	  <td>Status</td>	 <td>0x01</td>	       <td>0x03 - 0xFF</td>  <td>read</td></tr>
	<tr>	  <td>Command</td>	 <td>0x02</td>	       <td>0xE0 - 0xFF</td>  <td>read</td></tr>
      </table>
      </behavior>

    <behavior name="parallel i/o">

      In the default output-only mode, a data byte written to the
      <attribute>Port</attribute> control register is transmitted bit-by-bit to the
      PD0..PD7 output pins.  
     
      The parallel port controller model may be switched into the
      input mode by using the appropriate combination of signals on
      the BIDEN pin, the I/O Select register, and a bit in the Control
      register.  In this mode, signals driven onto the PD0..PD7 input
      pins are forwarded to the <attribute>Port</attribute> control register.

      The usual parallel port handshaking signals (STROBE, ACK, ERROR,
      ERROR, BUSY, PE) are used to carry out the Centronics printer
      protocol.  The appropriate pins use an "active-low" polarity,
      which means that zero is interpreted as an asserted signal, and
      non-zero as a deasserted signal.  Tri-state signals in hardware
      are not specifically modelled.
      </behavior>


    <behavior name="reset">
      When the RESET input pin is driven, control registers and pins
      return to their usual power-on states.
    </behavior>

    <convention name="functional" supported="true" />
    <convention name="save/restore" supported="true" />
    <convention name="triggerpoints" supported="true" />

  </func>
  <env>

  <title>Related components</title>

    <p>This component is customarily attached to a source of a reset
      signal.  The PD0..PD7 pins may be connected to simulated
      switches or indicators as needed.</p>

    <code>
	new hw-parport-ps/2 pport
	new hw-cpu-foo cpu
	new hw-mapper-basic mapper
	new hw-blinker-light led
	connect-pin main starting -> pport RESET
	connect-pin pport INTP -> cpu interrupt
	connect-pin pport PD0 -> led signal
	connect-bus mapper [0x3f0-0x3f8,4,1] pport Bus
    </code>
  </env>

  <refs>
    <ul>
    <li><a href="http://imeg.com/jadtech/ieee.htm">http://imeg.com/jadtech/ieee.htm</a></li>
    <li><a href="http://www.exar.com/products/st16c552_a.html">http://www.exar.com/products/st16c552_a.html</a></li>
    </ul>
  </refs>

</defcomplib>

=== yaomeiguan/epiphany-sourceware/sid/component/rtc/hw-rtc-ds1x42.xml
<?xml version="1.0" ?>
<!DOCTYPE defcomplib SYSTEM "http://sources.redhat.com/sid/component.dtd">

<defcomplib lib="librtc.la" dlsym="rtc_component_library">

  <defcomponent name="hw-rtc-ds1x42" type="abstract">

    <defpin name="clock" direction="in" behaviors="timekeeping"/>
    <defpin name="clock-control" direction="out" legalvalues="positive number" behaviors="frequency testing" />
    <defpin name="clock-event" direction="in" behaviors="frequency testing" />

    <defbus name="read-write-port" addresses="0x0 - 0x7FF" accesses="read/write byte-wide" behaviors="register access"/>

    <defattribute name="epoch-time" legalvalues="uint 32" behaviors="timekeeping"/>
    <defattribute name="year" category="register" legalvalues="0..99" behaviors="register access"/>
    <defattribute name="month" category="register" legalvalues="1..12" behaviors="register access"/>
    <defattribute name="date" category="register" legalvalues="1..31" behaviors="register access"/>
    <defattribute name="day-of-week" category="register" legalvalues="1..7" behaviors="register access"/>
    <defattribute name="hour" category="register" legalvalues="0..23" behaviors="register access"/>
    <defattribute name="minute" category="register" legalvalues="0..59" behaviors="register access"/>
    <defattribute name="second" category="register" legalvalues="0..59" behaviors="register access"/>
    <defattribute name="state-snapshot" legalvalues="opaque" behaviors="state save/restore"/>
    <defattribute name="tk xclock clone" legalvalues='"hw-visual-clock"' behaviors="component gui"/>
    
    <defaccessor name="memory-bus" accesses="byte-wide" behaviors="register access"/>

    <variants>
      <defcomponent name="hw-rtc-ds1642" type="concrete" />
      <defcomponent name="hw-rtc-ds1742" type="concrete" >
	<defattribute name="century" category="register" legalvalues="19..25" behaviors="register access"/>
      </defcomponent>
    </variants>        

  </defcomponent>

  <synop>The Dallas DS1642 and DS1742 are time-keeping NVRAM devices.
    The DS1742 is Y2K compliant as it maintains a century field in a
    section of NVRAM that was previously reserved by Dallas in the
    DS1642.
  </synop>
  <func>
    <modelling>
      <p>
	The DS1x42 components model real time using a single pin that can be
	driven at a simulated interval representing one second.  For
	modelling time in the target domain, a target scheduler may be used.
	For modelling real "wall-clock" time, the host scheduler may be
	used.</p>
  
      <p>
	The DS1x42 have a "frequency test" function that involves toggling
	the least significant bit of the <name>seconds</name> register at an idealized
	frequency of 512Hz.  When managed by a sid scheduler component, the
	actual frequency is around 500Hz.</p>
    </modelling>

    <behavior name="timekeeping">
      <p>Whenever the <pin>clock</pin> input is driven, it is
      interpreted as a signal that one second has passed.  An internal
      counter is incremented and all the time-related registers are
      recomputed.  The counter is accessible by the
      <attribute>epoch-time</attribute> attribute.</p></behavior>

    <behavior name="frequency testing">
      <p>When the
	<pin>clock-control</pin> and
	<pin>clock-event</pin> pin-pair is connected
	to an external scheduler, the DS1642 standard <name>test bit</name> is
	toggled at an approximate simulated frequency.
      </p>
    </behavior>

    <behavior name="register access">
      <p>
	The DS1642/DS1742 control registers and 2048-byte NVRAM are
	accessed across the
	<bus>read-write-port</bus> bus for byte-wide
	operations.  The control registers are also exposed as attributes.</p>

      <p>
	This family of parts includes 2KB of non-volatile RAM.  This
	component does not explicitly model this memory.  Instead, it
	interacts through the
	<accessor>memory-bus</accessor> accessor with an external
	memory like <complib>hw-memory-ram/rom-basic</complib>.</p>
      
    </behavior>

    <convention name="functional" supported="true" />
    <convention name="save/restore" supported="true" />
    <convention name="triggerpoints" supported="true">
      <p>
      They support setting triggerpoints on the state of data with the following
      names:</p>
      <table>
	<tr>
	  <td>
	    <name>epoch-time</name></td>
	  <td>Canonical internal representation of time.</td></tr>
	<tr>
	  <td>
	    <name>oscillating</name></td>
	  <td>The oscillator is connected.</td></tr>
	<tr>
	  <td>
	    <name>write-mode</name></td>
	  <td>The device is in write mode, for updates.</td></tr></table>
	  
    </convention>

  </func>
  <env>
    <ul>
      <title>Related components</title>
      <li>
	<p>
	  The 2KB of non-volatile memory included in these parts is not
	  explicitly modeled by this component.  Instead, it uses the
	  "memory-bus" accessor to interact with an external memory like
	  <complib>hw-memory-ram/rom-basic</complib>:</p>
	<code>
	  new hw-memory-ram/rom-basic nvram
	  set nvram size 2048
	  connect-bus rtc memory-bus nvram read-write-port</code>
      </li>
      
      <li>	
	<p>
	  In order to enable the "frequency test" function, you need to
	  couple an external scheduler to this component. The following is
	  an example of how to configure such a connection between a
	  scheduler and the DS1742 component:</p>
	<code>
	  new sid-sched-host-accurate sched
	  new hw-rtc-ds1742 rtc
	  set sched num-clients 2
	  set sched 0-regular? 1
	  set sched 0-time 1000 # 1 sec
	  connect-pin sched 0-event -&gt; rtc clock
	  connect-pin rtc clock-control -&gt; sched 1-control
	  connect-pin rtc clock-event &lt;- sched 1-event</code></li>      
    
      <li>
	<p>
	  The <complib>hw-visual-clock</complib> component is a candidate gui for this
	  component.</p>
	<code>
	  new hw-rtc-ds1742 rtc
	  new hw-visual-clock rtc-gui
	  relate rtc-gui "your rtc friend" rtc</code></li>
    </ul>
    <ul>
      <title>Host system</title>
      <li>
	<p>
	  These components rely on the accuracy and integrity of UTC time
	  maintained by the host, as the time and date are initialized
	  when the component is instantiated. The UNIX time() system call
	  is used to acquire the time.</p></li></ul>
  </env>
  <refs>  Dallas Semiconductor DS1642 data sheet, revision 031698; DS1742 data
    sheet, revision 091498. Available
    <a type="url" href="http://www.dalsemi.com/Prod_info/Time_Keep/index.html">online</a>,
    or in our <a type="techdoc" href="ds1642">local archives</a>.
  </refs>

</defcomplib>
